### ISSUE TITLE
[Bug] Login return 401

### ISSUE THREAD

**Issue by AhmedmmAli** [webysther/hoppscotch-docker#2]
I have tried to setup the hoppscotch using the latest docker image, everything is working fine but the login part.
I added microsoft and github credentiols and both return 401 in the call back,
I have also defined the 
schema=http,
ENABLE_API=true
MICROSOFT_CLIENT_ID=****
MICROSOFT_CLIENT_SECRET=*****
MICROSOFT_CALLBACK_URL=https://URL:3170/v1/auth/microsoft/callback
Mode=team

**Comment by webysther** [comment]
Hi, first things first, try the login using the e-mail, test if the login works when choose the option using email, look the log to url to login and tell me if works, as far I know, any oauth requires https.

**Comment by webysther** [comment]
No response.
